export const projects = [
	{
		title: 'Messenger Clone',
		skills: [
			'React',
			'Next.js',
			'TailwindCSS',
			'NextAuth',
			'React Hook Form',
			'Cloudinary',
			'Zustand',
			'Prisma',
			'MongoDB',
			'Pusher',
		],
		desc: 'The goal of this project was to hone my Next.js and Typescript skills and challenge myself with Pusher, a real-time chatting API. I learned how to send, receive, and delete messages in real-time. This implementation will be a key part of my upcoming passion project.',
		imageUrl: '/assets/images/messenger-clone.png',
		githubUrl: 'https://github.com/hmongdev/messenger-clone',
		deployUrl: 'https://hmongdev-messenger.vercel.app/',
	},
	{
		title: 'Evently',
		skills: [
			'React',
			'Next.js',
			'TailwindCSS',
			'Shadcn',
			'React Hook Form',
			'Zod',
			'Uploadthing',
			'React-Datepicker',
			'MongoDB',
			'Clerk',
			'Stripe',
		],
		desc: 'The goal of this project was to become familiar with integrating Stripe into an event-based management app, similar to Meetup.com or Eventbrite. In the future, I plan to integrate Stripe payment into my passion project and this was a simple full-stack project to do that.',
		imageUrl: '/assets/images/evently.png',
		githubUrl: 'https://github.com/hmongdev/evently',
		deployUrl: 'https://evently-hmongdev.vercel.app/',
	},
	{
		title: 'meetcute v1.0',
		skills: [
			'React',
			'TypeScript',
			'TailwindCSS',
			'Shadcn',
			'Tanstack Query',
			'React Hook Form',
			'Zod',
		],
		desc: 'The goal of this project was to create a prototype of my passion project, a social media / dating app. This prototype features creating, liking, saving, and searching posts to increase user engagement.',
		imageUrl: '/assets/images/meetcute.png',
		githubUrl: 'https://github.com/hmongdev/meetcute-v1.0',
		deployUrl: 'https://meetcute-v1.vercel.app/',
	},
	{
		title: 'Threads Clone',
		skills: [
			'React',
			'Next.js',
			'TypeScript',
			'TailwindCSS',
			'Shadcn',
			'React Hook Form',
			'Zod',
			'Uploadthing',
			'MongoDB',
			'Clerk',
		],
		desc: 'The goal of this project was to challenge myself with new technologies like Shadcn, React Hook Form, Zod, Uploadthing, MongoDB, and Clerk. The Threads clone allows users to create, read, edit, and delete posts and comments. I did not spend much time with styling and believe the app could use a theme overhaul. In my next project, I plan to transfer these features and expand on them so you can vote on posts, similar to Reddit. In addition, I will be moving to react native and postgres to build exclusively for mobile devices and customize the database',
		imageUrl: '/assets/images/threads-clone.png',
		githubUrl: 'https://github.com/hmongdev/threads-clone',
		deployUrl: 'https://threads-clone-yang.vercel.app/',
	},
	{
		title: 'Car Hub',
		skills: ['React', 'Next.js', 'TypeScript', 'TailwindCSS'],
		desc: 'This is a single-page, landing page utilizing the Cars API and TailwindCSS to become familiar with Next.js and TypeSript. Before this, I had coded primarily in React and JavaScript, so this was a challenge for me.',
		imageUrl: '/assets/images/car-showcase.png',
		githubUrl: 'https://github.com/hmongdev/car-showcase',
		deployUrl: 'https://car-showcase-nextjs-coral.vercel.app/',
	},
	{
		title: 'Promptopia',
		skills: ['React', 'TailwindCSS', 'MongoDB'],
		desc: "This is an earlier project I used to focus on TypeScript and Next.js. It's a simple landing page that allows users to sign in via Google, create a post containing a chatgpt prompt, and add tags to save for later use. The site also features the ability to search and filter posts for tags or a username for easy access. The website is fully mobile-responsive.",
		imageUrl: '/assets/images/promptopia.png',
		githubUrl: 'https://github.com/hmongdev/promptopia',
		deployUrl: 'https://promptopia-omega-steel.vercel.app/',
	},
];


export const jobHistory = [
	{
		company: 'Hydra',
		position: 'Front-End Software Engineer',
		location: 'MN',
		years: '2024 - 2024',
	},
	{
		company: 'Prime Digital Academy',
		position: 'Fullstack Engineering Student',
		location: 'MN',
		years: '2022 - 2022',
	},
	{
		company: 'Software For Good',
		position: 'Software Engineer Apprentice',
		location: 'MN',
		years: '2021 - 2022',
	},
	{
		company: 'Colder Products Company',
		position: 'Cell Lead',
		location: 'MN',
		years: '2021 - 2021',
	},
	{
		company: 'The Cove',
		position: 'Team Member',
		location: 'MN',
		years: '2019 - 2021',
	},
	{
		company: 'UMN - Off-Campus Living (OCL)',
		position: 'Renter Education Liasion',
		location: 'MN',
		years: '2018 - 2019',
	},
	{
		company: 'Restorative Justice Community Action',
		position: 'Intake and Administrative Assistant',
		location: 'MN',
		years: '2017 - 2018',
	},
	{
		company: 'Goodwill Easter Seals',
		position: 'Team Member',
		location: 'MN',
		years: '2016 - 2017',
	},
	{
		company: 'Noodles and Co.',
		position: 'Team Member',
		location: 'MN',
		years: '2015 - 2017',
	},
];

export const routes = [
	{
		name: 'Portfolio',
		icon: 'folders',
	},
	{
		name: 'Experience',
		icon: 'school',
	},
	{
		name: 'Contact',
		icon: 'contact',
	},
	{
		name: 'About',
		icon: 'bookA',
	},
];